### ISSUE TITLE
Missing binary builds for Python 3.8

### ISSUE THREAD

**Issue by ehsanonline** [cher-nov/cryptg#3]
I tried to install this on windows 10 but i got this error:
```
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\e\desktop\newfol~2\env\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\e\\AppData\\Local\\Temp\\pip-install-khpqbheh\\cryptg\\setup.py'"'"'; __file__='"'"'C:\\Users\\e\\AppData\\Local\\Temp\\pip-install-khpqbheh\\cryptg\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\e\AppData\Local\Temp\pip-install-khpqbheh\cryptg\pip-egg-info'
         cwd: C:\Users\e\AppData\Local\Temp\pip-install-khpqbheh\cryptg\
    Complete output (102 lines):
    Traceback (most recent call last):
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\e\AppData\Local\Temp\easy_install-mzssp6r5\cffi-1.13.1\setup.py", line 127, in <module>
      File "C:\Users\e\AppData\Local\Temp\easy_install-mzssp6r5\cffi-1.13.1\setup.py", line 105, in uses_msvc
      File "c:\users\e\appdata\local\programs\python\python38\Lib\distutils\command\config.py", line 225, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "c:\users\e\appdata\local\programs\python\python38\Lib\distutils\command\config.py", line 132, in _compile
        self.compiler.compile([src], include_dirs=include_dirs)
      File "c:\users\e\appdata\local\programs\python\python38\Lib\distutils\_msvccompiler.py", line 360, in compile
        self.initialize()
      File "c:\users\e\appdata\local\programs\python\python38\Lib\distutils\_msvccompiler.py", line 253, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\msvc.py", line 171, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\msvc.py", line 1075, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\msvc.py", line 547, in __init__
        vc_ver or self._find_latest_available_vs_ver())
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\msvc.py", line 561, in _find_latest_available_vs_ver
        raise distutils.errors.DistutilsPlatformError(
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\e\AppData\Local\Temp\pip-install-khpqbheh\cryptg\setup.py", line 63, in <module>
        main(sys.argv)
      File "C:\Users\e\AppData\Local\Temp\pip-install-khpqbheh\cryptg\setup.py", line 19, in main
        setup(
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\dist.py", line 717, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
        return installer(requirement)
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\dist.py", line 787, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
        raise
      File "c:\users\e\appdata\local\programs\python\python38\Lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\users\e\appdata\local\programs\python\python38\Lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\e\AppData\Local\Temp\easy_install-mzssp6r5\cffi-1.13.1\setup.py", line 127, in <module>
      File "C:\Users\e\AppData\Local\Temp\easy_install-mzssp6r5\cffi-1.13.1\setup.py", line 105, in uses_msvc
      File "c:\users\e\appdata\local\programs\python\python38\Lib\distutils\command\config.py", line 225, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "c:\users\e\appdata\local\programs\python\python38\Lib\distutils\command\config.py", line 132, in _compile
        self.compiler.compile([src], include_dirs=include_dirs)
      File "c:\users\e\appdata\local\programs\python\python38\Lib\distutils\_msvccompiler.py", line 360, in compile
        self.initialize()
      File "c:\users\e\appdata\local\programs\python\python38\Lib\distutils\_msvccompiler.py", line 253, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\msvc.py", line 171, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\msvc.py", line 1075, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\msvc.py", line 547, in __init__
        vc_ver or self._find_latest_available_vs_ver())
      File "c:\users\e\desktop\newfol~2\env\lib\site-packages\setuptools\msvc.py", line 561, in _find_latest_available_vs_ver
        raise distutils.errors.DistutilsPlatformError(
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I had the Microsoft Visual C++ 2017 14.12 installed, and I could not install 2015 version because the installed wont allow it unless I uninstall the current version.
So i uninstalled the 2017 and installed the 2015 but I got the same error again!

**Comment by ehsanonline** [comment]
fixed it by the help of this tutorial:
https://medium.com/@jacky_ttt/day060-fix-error-microsoft-visual-c-14-0-is-required-629413e798cd

**Comment by Lonami** [comment]
As @cher-nov pointed to me out, you seem to be using Python 3.8, and we currently don't provide binary builds for it. Once [`cibuildwheel`](https://github.com/joerick/cibuildwheel) supports said Python version, we can start providing them.

**Comment by cher-nov** [comment]
Fixed: https://ci.appveyor.com/project/cher-nov/cryptg/builds/28831324
